name: macos_arm64 

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'README_zh_HK.md'
      - 'README_ja_JP.md'
      - 'DEVELOPNOTE.md'
      - 'CHANGELOG.md'
      - 'TODO.md'
      - '.readthedocs.yaml'
    tags:
      - V**
  workflow_dispatch:

jobs:
  macos_arm64:
    runs-on: flyci-macos-large-latest-m1

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.3'
          modules: 'qt5compat qtwebsockets qtserialport qtmultimedia'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          ruby - e  "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null  2 > /dev/null
          brew install --build-from-source cmake
          brew install create-dmg

      - name: build libssh2
        run: |
          cd depend
          export PATH=$Qt6_DIR/bin:$PATH
          ./build_libssh2.sh
          sudo cp -R ./output /usr/local/

      - name: Build all
        run: |
          git fetch --tags --force
          sed -i'.original' -e 's/--long --dirty/--long/g' ./tools/generate_info.sh
          sed -i'.original' -e 's/QT_DIR=\/opt\/Qt6.2.0\/6.2.0\/gcc_64/QT_DIR=$(cd "$(dirname "$0")";pwd)\/..\/Qt\/6.5.3\/macos/g' build_dmg.sh
          sed -i'.original' -e 's/LIBSSH2_DIR=\/libssh2/LIBSSH2_DIR=\/usr\/local\/output/g' ./lib/qtssh/qtssh.pri
          ./build_dmg.sh
          mv ./build_release/out/quardCRT.dmg ./build_release/out/quardCRT_arm64.dmg

      - name: Upload build asserts
        uses: actions/upload-artifact@v4.0.0
        with:
          name: quardCRT_macos_arm64
          path: |
            ./dmgOut/*.dmg

      - name: Run tests
        run: |
          sudo hdiutil attach ./build_release/out/quardCRT_arm64.dmg
          /Volumes/quardCRT/quardCRT.app/Contents/MacOS/quardCRT --version
        