name: windows

on:
  push:
    branches: [ main, dev-ssh2 ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - 'CHANGELOG.md'
      - '.readthedocs.yaml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'doc/**'
      - 'docs/**'
      - 'README.md'
      - 'README_zh_CN.md'
      - 'DEVELOPNOTE.md'
      - 'CHANGELOG.md'
      - '.readthedocs.yaml'
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          arch: win64_mingw
          version: '6.5.3'
          modules: 'qt5compat qtwebsockets qtserialport qtmultimedia'
          aqtversion: ==3.1.7

      - name: Install prerequisites
        run: |
          Choco-Install -PackageName innosetup --force
          Choco-Install -PackageName cmake --force

      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64

      #- name: Build winpty
      #  shell: msys2 {0}
      #  run: |
      #    pacman --noconfirm -S make gcc
      #    cd depend
      #    export PATH=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
      #    ./build_winpty_ms.sh

      - name: build libssh2
        shell: msys2 {0}
        run: |
          pacman --noconfirm -S make cmake autoconf automake bison diffutils libtool texinfo xmlto
          pacman --noconfirm -S base-devel msys2-devel mingw-w64-{x86_64,i686}-toolchain 
          cd depend
          export PATH=/c/ProgramData/Chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH
          ./build_libssh2_mingw.sh
          mkdir /d/libssh2
          mkdir /d/libssh2/include
          mkdir /d/libssh2/lib
          cp -r ./output/include/* /d/libssh2/include/
          cp -r ./output/lib/* /d/libssh2/lib/

      - name: Install winpty
        run: |
          cd D:/
          curl -L https://github.com/rprichard/winpty/releases/download/0.4.3/winpty-0.4.3-msys2-2.7.0-x64.tar.gz -o winpty-0.4.3-msys2-2.7.0-x64.tar.gz
          tar -xvf winpty-0.4.3-msys2-2.7.0-x64.tar.gz
          mv winpty-0.4.3-msys2-2.7.0-x64 winpty

      - name: Build all
        run: |
          git fetch --tags --force
          git describe --always --long --abbrev=10 --tags | ./tools/awk/awk.exe '{print \"\\\"\"$0\"\\\"\"}'  > git_tag.inc
          ./tools/sed/sed.exe -i "s/git_tag.inc/git_tag.ci.inc/g" quardCRT.pro
          ./tools/sed/sed.exe -i "s/QT_DIR=C:\/Qt\/Qt6.2.0\/6.2.0\/mingw81_32\/bin/QT_DIR=%Qt5_Dir%/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/QT_TOOLS_DIR=C:\/Qt\/Qt6.2.0\/Tools\/mingw810_32\/bin/QT_TOOLS_DIR=C:\/ProgramData\/Chocolatey\/lib\/mingw\/tools\/install\/mingw64\/bin/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/mingw32-make -j8/mingw32-make -j1/g" ./build_setup.bat
          ./tools/sed/sed.exe -i "s/WINPTY_DIR=D:\\quardCRT\\depend\\winpty/WINPTY_DIR=D:\\winpty/g" ./lib/ptyqt/ptyqt.pri
          ./tools/sed/sed.exe -i "s/LIBSSH2_DIR=\/libssh2/LIBSSH2_DIR=D:\\libssh2/g" ./lib/qtssh/qtssh.pri
          ./build_setup.bat

      - name: Upload build asserts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: quardCRT_windows
          path: |
            ./InnoSetup/quardCRT_setup.exe

      - name: Run tests
        run: |
          ./InnoSetup/build/quardCRT.exe --version
